################################################################################
# TYPE: Package
# FILENAME: estores.yaml
# NAME: Controlo dos estores
################################################################################

#### Dispositivos
#### Sonoff Dual de contactos secos botoes trabalham separados 
#### 

#### website

################################################################################
#### SCRIPTS
################################################################################

#script:

#### 

################################################################################
## SHELL COMMAND
################################################################################

#shell_command: 

#### 

################################################################################
## INPUT TEXT
################################################################################

#input_text:

#### 

################################################################################
#### INPUT SELECT
################################################################################

#input_select:

#### 

################################################################################
#### INPUT BOOLEANS
################################################################################

#input_boolean:

#### 

################################################################################
#### INPUT NUMBER (OLD INPUT_SLIDER)
################################################################################

#input_number:

#### 

################################################################################
#### INPUT DATE TIME
################################################################################

#input_datetime:

#### 

################################################################################
#### REST COMMANDS
################################################################################

#rest_command:

#### 

################################################################################
#### SENSORS
################################################################################

#sensor:

#### 

################################################################################
#### SENSOR TEMPLATES
################################################################################

####

################################################################################
## BINARY SENSORS
################################################################################

#binary_sensor:

#### 

################################################################################
#### BINARY SENSOR TEMPLATES
################################################################################

####

################################################################################
## SWITCHES
################################################################################

switch:
# Dual Sonoff R2 estore
  - platform: mqtt
    name: "Abrir"
    #icon: mdi:window-shutter-open
    command_topic: "cmnd/estores/power1"
    state_topic: "stat/estores/POWER1"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    #retain: false
  - platform: mqtt
    name: "Fechar"
    #icon: mdi:window-shutter
    command_topic: "cmnd/estores/power2"
    state_topic: "stat/estores/POWER2"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    #retain: false

################################################################################
## LIGHTS
################################################################################

#light:

#### 

################################################################################
## ALERTS
################################################################################

#alert:

#### 

################################################################################
#### CUSTOMIZE
################################################################################

homeassistant:
# 
  customize:
    switch.abrir:
        icon: mdi:window-shutter-open
    switch.fechar:
        icon: mdi:window-shutter
#### 

################################################################################
#### AUTOMATION
################################################################################

automation:

#Inicio fechar estore ao por do sol 
- alias: "Fechar estore ao por do sol"
  trigger:
    platform: sun
    # Possible values: sunset, sunrise
    event: sunset
    # Optional time offset. This example will trigger 45 minutes before sunrise.
    offset: '-00:30:00'
  action:
    service: switch.turn_on
    entity_id: switch.fechar
#Fim Fechar estore ao por do sol 

#Tempo de abertura fecho estore
- alias: Abrir os estores durante x tempo
  trigger:
    platform: state
    entity_id: switch.abrir
    from: 'off'
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 20
  action:
    service: switch.turn_off
    entity_id: switch.abrir
    
- alias: Fechar os estores durante x tempo
  trigger:
    platform: state
    entity_id: switch.fechar
    from: 'off'
    to: 'on'
    for: '00:00:30'

      #hours: 0
      #minutes: 0
      #seconds: 20
  action:
    service: switch.turn_off
    entity_id: switch.fechar
# Fim Tempo de abertura fecho estore

